e = Exception("my exception")

print(dir(e))
def shit():
    raise Exception('shit')
    return "value"